### ISSUE TITLE
Broken link to slides deck

### ISSUE THREAD

**Issue by DmitriyMaksimov** [datastaxdevs/workshop-sql-to-nosql-migration#1]
Link to slides deck `https://github.com/datastaxdevs/workshop-sql-to-nosql-migration/blob/main/slides.pdf`  is broken

**Comment by HadesArchitect** [comment]
Thank you! It will be updated right before the workshop.

**Comment by HadesArchitect** [comment]
Meanwhile we invite you to join our `Cassandra Day Russia AMA Afterparty` tomorrow! Ask questions here https://dtsx.io/cdrus-ama and join the event stream: https://youtu.be/FlzjLV_7olE

**Comment by HadesArchitect** [comment]
Fixed
